namespace HermesProxy.World.Enums.V3_3_5a_12340;

// Legacy WotLK 3.3.5a response codes. Distinct from V2_4_3 (TBC) — the
// CharDelete / CharLogin / CharName ranges shift up. Without this enum,
// VersionChecker.GetResponseCodesEnum routed 3.3.5a backends to the V2_4_3
// table and the name-based ConvertResponseCodesValue lookup returned the
// integer string for any value V2_4_3 didn't define (e.g. 71 → "71" → 71),
// which the V3_4_3 client misread as CHAR_DELETE_FAILED_DEPRECATED1 → popup.
public enum ResponseCodes : byte
{
    Success = 0,
    Failure = 1,
    Cancelled = 2,
    Disconnected = 3,
    FailedToConnect = 4,
    Connected = 5,
    VersionMismatch = 6,
    CstatusConnecting = 7,
    CstatusNegotiatingSecurity = 8,
    CstatusNegotiationComplete = 9,
    CstatusNegotiationFailed = 10,
    CstatusAuthenticating = 11,
    RealmListInProgress = 35,
    RealmListSuccess = 36,
    RealmListFailed = 37,
    RealmListInvalid = 38,
    RealmListRealmNotFound = 39,
    AccountCreateInProgress = 40,
    AccountCreateSuccess = 41,
    AccountCreateFailed = 42,
    CharListRetrieving = 43,
    CharListRetrieved = 44,
    CharListFailed = 45,
    CharCreateInProgress = 46,
    CharCreateSuccess = 47,
    CharCreateError = 48,
    CharCreateFailed = 49,
    CharCreateNameInUse = 50,
    CharCreateDisabled = 51,
    CharCreatePvpTeamsViolation = 52,
    CharCreateServerLimit = 53,
    CharCreateAccountLimit = 54,
    CharCreateServerQueue = 55,
    CharCreateOnlyExisting = 56,
    CharCreateExpansion = 57,
    CharCreateExpansionClass = 58,
    CharCreateLevelRequirement = 59,
    CharCreateUniqueClassLimit = 60,
    CharCreateCharacterInGuild = 61,
    CharCreateRestrictedRaceclass = 62,
    CharCreateCharacterChooseRace = 63,
    CharCreateCharacterArenaLeader = 64,
    CharCreateCharacterDeleteMail = 65,
    CharCreateCharacterSwapFaction = 66,
    CharCreateCharacterRaceOnly = 67,
    CharCreateCharacterGoldLimit = 68,
    CharCreateForceLogin = 69,
    CharDeleteInProgress = 70,
    CharDeleteSuccess = 71,
    CharDeleteFailed = 72,
    CharDeleteFailedLockedForTransfer = 73,
    CharDeleteFailedGuildLeader = 74,
    CharDeleteFailedArenaCaptain = 75,
    CharLoginInProgress = 76,
    CharLoginSuccess = 77,
    CharLoginNoWorld = 78,
    CharLoginDuplicateCharacter = 79,
    CharLoginNoInstances = 80,
    CharLoginFailed = 81,
    CharLoginDisabled = 82,
    CharLoginNoCharacter = 83,
    CharLoginLockedForTransfer = 84,
    CharLoginLockedByBilling = 85,
    CharNameSuccess = 87,
    CharNameFailure = 88,
    CharNameNoName = 89,
    CharNameTooShort = 90,
    CharNameTooLong = 91,
    CharNameInvalidCharacter = 92,
    CharNameMixedLanguages = 93,
    CharNameProfane = 94,
    CharNameReserved = 95,
    CharNameInvalidApostrophe = 96,
    CharNameMultipleApostrophes = 97,
    CharNameThreeConsecutive = 98,
    CharNameInvalidSpace = 99,
    CharNameConsecutiveSpaces = 100,
    CharNameRussianConsecutiveSilentCharacters = 101,
    CharNameRussianSilentCharacterAtBeginningOrEnd = 102,
    CharNameDeclensionDoesntMatchBaseName = 103
}
